Check if scratch ensemble is empty
equinor/webviz-subsurface pull request #457
Opened 2020-09-29 14:57 UTC by HansKallekleiv

--

### Contributor checklist

- [ ] :tada: This PR closes #315 .
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Check if scratch ensemble is empty, i.e. no target file exists

2020-09-29 15:12 UTC, asnyv commented on webviz_subsurface/__init__.py
> +                    f"{ensemble_name} located at {ensemble_path}. "
Add something even more explicit? E.g. "This can e.g. occur when running ERT if no simulations are finished, or all simulations failed."?

2020-09-29 17:39 UTC, asnyv requested changes

2020-09-29 17:39 UTC, asnyv commented on webviz_subsurface/__init__.py
> +                    f"{ensemble_name} located at {ensemble_path}. This an occur when running "
```suggestion
                    f"{ensemble_name} located at {ensemble_path}. This can occur when running "
```

2020-09-29 18:03 UTC, asnyv approved these changes
👍 🎉

2020-09-30 14:28 UTC, anders-kiaer approved these changes

2020-09-30 17:15 UTC, anders-kiaer commented on webviz_subsurface/__init__.py
> +                    "ERT if no simulations are finished, or all simulations has failed."
```suggestion
                    "ERT if no simulations are finished, or all simulations have failed."
```

2020-10-01 16:17 UTC, merged