Ahmanalysis plugin
equinor/webviz-subsurface pull request #478
Opened 2020-10-28 14:01 UTC by mareco701

This is to add a new plugin to visualize assisted history matching analysis (how much update in parameters observations trigger, and which observations trigger an update of a parameter when all observations are considered)
---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

2020-10-28 14:31 UTC, anders-kiaer commented
Thanks for the PR @mareco701. Changed the status of this to "draft" while waiting for things to go :green_circle:.

Looks like a module is currently missing according to the logs?
`ModuleNotFoundError: No module named 'data_analysis_test1'`

2020-10-28 20:18 UTC, anders-kiaer commented on setup.py
> +            "AssistedHistoryMatchingAnalysis = data_analysis_test1.plugins:AssistedHistoryMatchingAnalysis",
```suggestion
            "AssistedHistoryMatchingAnalysis = webviz_subsurface.plugins:AssistedHistoryMatchingAnalysis",
```
...and you should then also add it to `webviz_subsurface/plugins/__init__.py` 🙂

2020-10-28 20:20 UTC, anders-kiaer commented on webviz_subsurface/plugins/_ahm_analysis_plugin.py
> +class AHMAnalysisPlugin(WebvizPluginABC):
The plugin name here should be consistent with what is used in `setup.py`.

2020-10-29 16:30 UTC, anders-kiaer commented
Looks good :+1:  Changing temporarily these lines https://github.com/equinor/webviz-subsurface/blob/5f5dc6596ce2a4122b9c53c1698a1170b1f47d5d/.github/workflows/subsurface.yml#L83-L86 to `mareco701` and `inc_test_for_ahmanalysis` would help in the last part of the review process by automatically testing against your new testdata PR (then we simply change those two lines back before `merge`).

2020-11-05 11:11 UTC, anders-kiaer commented
This looks ready for review now @mareco701 :+1: :tada:

2020-11-23 11:36 UTC, anders-kiaer requested changes
Nice plugin @mareco701. 

> Give path to input data: 

Should we remove this input box in the frontend, since it is already defined in the `yaml` file? In addition asking for file input will not work very well in :cloud: setting.

> Show default parameters distribution
> Show transformed parameters distribution (if available)

Then maybe at plugin startup you already know if the transformed distribution is available, and can hide (or disable/grey out) this option in order to simplify the UI? Since it is binary choice (default or transformed) maybe it can be a check box instead of two radio buttons?

Add a guided tour explaining what the uses sees? See https://github.com/equinor/webviz-subsurface/blob/f9062a639974518c4e51c726b57a5c0111810bb9/webviz_subsurface/plugins/_reservoir_simulation_timeseries.py#L256 for an example from another plugin.

> Filter observations: 
> Filter parameters: 

Maybe they should use e.g. `wcc.Select` instead of text input box? Both to make it easier to select among other options, and to ensure only valid options are entered (currently writing an non-existing parameter in the parameter filter results in an `IndexError`). See https://webviz-subsurface-example.azurewebsites.net/parameter-parallel-coordinates for an example using `wcc.Select`.

2020-11-23 11:36 UTC, anders-kiaer commented on webviz_subsurface/plugins/_ahm_analysis_plugin.py
> +                + ")",
```suggestion
                title=f"Parameter distribution for observation {obs} ({active_info.at["ratio", obs]})",
```

2020-11-23 11:36 UTC, anders-kiaer commented on webviz_subsurface/plugins/_ahm_analysis_plugin.py
> +            ],
```suggestion
            Output(self.ids("generate_table"), component_property="children"),
            Input(self.ids("inputpath_id"), component_property="value"),
            Input(self.ids("choice_id"), component_property="value"),
```

2020-11-23 11:36 UTC, anders-kiaer commented on webviz_subsurface/plugins/_ahm_analysis_plugin.py
> +    return input_filter
```suggestion
    return "_" if input_filter == "" else input_filter
```

2020-11-24 09:08 UTC, mareco701 commented on webviz_subsurface/plugins/_ahm_analysis_plugin.py
> +                + ")",
not changed since it made black fail

2020-11-25 19:26 UTC, HansKallekleiv approved these changes
Looks good! :+1:

2020-11-25 20:52 UTC, anders-kiaer approved these changes

2020-11-25 20:53 UTC, merged