Obey column_keys when storing unsmry data with frequency raw
equinor/webviz-subsurface pull request #531
Opened 2020-12-17 14:25 UTC by asnyv

Obeys selected `column_keys` when using `time_index` / `sampling` of `raw` (or the equivalent `None`) when loading and storing `UNSMRY` data.

Did some test on larger datasets than our test data, and it was a dramatic improvement. Saw peak memory usage reduced by up to **97%!**

Nevertheless, it is clear that we have memory issues: with this edit on my larger data set, peak memory usage during load and portable build was still more than 3 times higher than peaks when running the portable. 

Could also be that we should do the same for `daily` data frequency, as that is also quite high when it comes to reservoir simulation?
---

### Contributor checklist

- [X] :tada: This PR closes #528 

- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

2020-12-17 18:49 UTC, HansKallekleiv requested changes

2020-12-17 18:49 UTC, HansKallekleiv commented on webviz_subsurface/_models/ensemble_model.py
> +        print(time_index)
remove

2020-12-17 18:56 UTC, asnyv commented on webviz_subsurface/_models/ensemble_model.py
> +        print(time_index)
Fixed 👍
How did I miss that 🤔 😣

2020-12-18 08:27 UTC, HansKallekleiv approved these changes
LGTM 👍

2020-12-18 08:28 UTC, merged