Reformat ParameterParallelCoordinates and ParameterResponseCorrelation
equinor/webviz-subsurface pull request #556
Opened 2021-02-01 14:14 UTC by asnyv

Reformat ParameterParallelCoordinates and ParameterResponseCorrelation to simplify removal of duplicate summary data

---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

2021-02-03 20:01 UTC, HansKallekleiv requested changes
Some minor changes, otherwise LGTM 👍

2021-02-04 07:24 UTC, asnyv commented on .github/workflows/subsurface.yml
> +        sudo apt-get purge p7zip* yarn ruby-full adoptopenjdk* ghc* php7*
Already done in #557

2021-02-04 07:25 UTC, asnyv commented on .github/workflows/subsurface.yml
> +        # mypy --package webviz_subsurface --package tests
Fixed 👍

2021-02-04 09:08 UTC, HansKallekleiv approved these changes

2021-02-04 09:22 UTC, merged