Wellcompl history from summary
equinor/webviz-subsurface pull request #662
Opened 2021-06-07 11:52 UTC by lindjoha

This PR solves the problem of incomplete compdat OPEN/SHUT history coming from `ecl2df`. There is various problems with `ecl2df `exporting the connection history: it is not picking up lumps of connections being closed by WELOPEN and it could never pick up completions closed with ACTIONS. For history, all the information would be in the schedule file, and it could in theory be solved in ecl2df, but not for predictions with f.ex ACTIONS.

This PR allows the user to pass to the plugin a connection status table, exported by an ERT workflow (EXPORT_CONNECTION_STATUS) for each realization. This data is extracted from the CPI summary data. The data is stored in `.parquet` format and has the following columns: WELL, I, J, K, OP/SH (similar to the ecl2df compdat export: https://equinor.github.io/ecl2df/usage/compdat.html). For each connection, there is one line for every time the connection status changes. It can only be OPEN or SHUT.

If this data is not passed to the plugin, the connection history is taken from the compdat export as before. So it's also possible to improve the compdat export from `ecl2df `and use that  (should be sufficient for history runs).

2021-06-21 18:45 UTC, anders-kiaer requested changes
👏 🚀 Minor comments below mostly.

2021-06-22 06:15 UTC, lindjoha commented on webviz_subsurface/ert_jobs/export_connection_status.py
> +"""
There is actually a way to that ERT can pick up documentation from the jobs and the DESCRIPTION has to do with that. I was planning to look into it. I have to add something to the jobs.py file.

2021-06-22 06:29 UTC, lindjoha commented on webviz_subsurface/_datainput/well_completions.py
> +    raise ValueError(f"Realization number not found for {filename}")
Yes, I agree. I will look into it.

2021-06-22 13:07 UTC, anders-kiaer submitted a review, later dismissed

2021-06-22 17:05 UTC, lindjoha commented on webviz_subsurface/_datainput/well_completions.py
> +    raise ValueError(f"Realization number not found for {filename}")
I have now rewritten the code to use fmu-ensemble to find the files.

2021-06-24 10:29 UTC, anders-kiaer approved these changes

2021-06-24 10:38 UTC, merged