Use ParameterModel in `VolumetricAnalysis` and `ParameterAnalysis`
equinor/webviz-subsurface pull request #700
Opened 2021-06-30 11:01 UTC by tnatt

Duplicate code lines for processing dataframes with parameter data existed in both the `VolumetricAnalysis` and the `ParameterAnalysis` plugins. The already existing `ParameterModel` also included this processing but was not used anywhere. 

This PR includes:
   - adding logic for identifying if ensembles are sensitivity runs into the `ParameterModel` 
   - change into using the `ParameterModel` in both the `InplaceVolumesModel` and the `ParameterAnalysis` plugin
---

### Contributor checklist

- [ ] :tada: This PR closes #699

2021-07-01 10:01 UTC, HansKallekleiv approved these changes

2021-07-01 10:05 UTC, anders-kiaer requested changes
Is this considered a bug fix? Or should we wait with merge until release early next week?

2021-07-01 10:24 UTC, tnatt commented
> Is this considered a bug fix? Or should we wait with merge until release early next week?

No, this was meant for the next release.

2021-08-12 07:07 UTC, anders-kiaer approved these changes

2021-08-23 14:38 UTC, merged