Seismic misfit improvements
equinor/webviz-subsurface pull request #844
Opened 2021-11-10 13:32 UTC by rnyb

*General improvements*

---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Reworked all colors. Use same symmetric colorscale for all types of attributes. Also new color scales for diff plot and error plot. Colorscales are included as global variables.
   - [ ] Prettyfied all hoverdata
   - [ ] New option for slice plot. show individual realizations
   - [ ] Keep user defined zoom during callback
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

2021-11-11 11:59 UTC, anders-kiaer requested changes
One comment - otherwise LGTM.

2021-11-11 11:59 UTC, anders-kiaer commented on webviz_subsurface/plugins/_seismic_misfit.py
> +                        df_polygon["name"] = name
Maybe you can use (needs to be tested):
```suggestion
                        df_polygon["name"] = Path(poly_file).stem.replace("_", " ")
```

2021-11-11 13:23 UTC, rnyb commented on webviz_subsurface/plugins/_seismic_misfit.py
> +                        df_polygon["name"] = name
Nice one, will fix.

2021-11-12 08:09 UTC, anders-kiaer approved these changes

2021-11-12 08:09 UTC, anders-kiaer commented on CHANGELOG.md
> +### Added
Does the change belong more under the `Changed` category?

2021-11-12 09:21 UTC, merged