Prod misfit arrow
equinor/webviz-subsurface pull request #938
Opened 2022-01-25 10:45 UTC by rnyb

Work In Progress

---

### Contributor checklist

- [ ] :tada: This PR closes #754.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

2022-03-29 07:07 UTC, lindjoha requested changes
I have started on a review, but will do more later

2022-03-29 12:25 UTC, rnyb commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +        logging.debug(f"Init done. Cummulative time: {time.time() - start}")
will do

2022-03-29 12:25 UTC, rnyb commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +    all_wells = []
The  `_check_well_collections` function is an older version of `_get_well_collections` function and not used anymore, so i can remove it altogether.

2022-03-29 12:41 UTC, rnyb commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +    all_wells = []
`all_wells = sorted(list(wells.values()))` will generate a list of lists so not sure if that would work as intended?

2022-03-29 13:11 UTC, rnyb commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +        all_collection_wells = []
If i understand it correctly I think this won't work (TypeError: unhashable type: 'list')

2022-03-30 06:57 UTC, lindjoha requested changes

2022-03-30 06:57 UTC, lindjoha commented on webviz_subsurface/plugins/_prod_misfit/_callbacks.py
> +        # # --- apply ensemble filter
Remove old code?

2022-03-30 06:57 UTC, lindjoha commented on webviz_subsurface/plugins/_prod_misfit/_callbacks.py
> +        selected_collection_wells.extend(well_collections[collection_name])
maybe like this? 
`selected_collection_wells = list(set([well_collections[name] for name in selected_collection_names])) `

2022-04-21 13:35 UTC, anders-kiaer commented on CHANGELOG.md
>  - [#988](https://github.com/equinor/webviz-subsurface/pull/988) - `ParameterAnalysis` and `PropertyStatistics` - Switched to the VectorSelector component, and other various improvements.
Add the good news about prod misfit added to changelog?

2022-04-21 13:35 UTC, anders-kiaer commented on webviz_subsurface/plugins/__init__.py
> +# from ._prod_misfit._plugin import ProdMisfit
```suggestion
```
Remove?

2022-04-21 13:36 UTC, anders-kiaer commented on webviz_subsurface/plugins/_prod_misfit/_callbacks.py
> +# from ._property_serialization import GraphFigureBuilder
Remove?
```suggestion
```

2022-04-21 13:37 UTC, anders-kiaer commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +        if len(undefined_wells) > 0:
```suggestion
        if undefined_wells:
```

2022-04-21 13:39 UTC, anders-kiaer commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +    if len(vectors) == 0:
```suggestion
    if not vectors:
```

2022-04-21 13:40 UTC, anders-kiaer commented on webviz_subsurface/plugins/_prod_misfit/_plugin.py
> +    if len(drop_list) > 0:
```suggestion
    if drop_list:
```

2022-04-23 06:29 UTC, anders-kiaer approved these changes

2022-04-23 06:31 UTC, merged